{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform float alpha;\n\nvec4 fragColor;\n\nvec3 flutterBlue;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    flutterBlue = vec3(0.01960784383118152618408203125, 0.3254902064800262451171875, 0.69411766529083251953125);\n    vec2 st = FLT_flutter_local_FlutterFragCoord() / resolution;\n    vec3 color = vec3(0.0);\n    vec3 percent = vec3((st.x + st.y) / 2.0);\n    fragColor = vec4(flutterBlue, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 0,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "alpha",
      "rows": 1,
      "type": 10
    }
  ]
}