{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / iResolution;\n    float ratio = iResolution.x / iResolution.y;\n    uv = vec2((uv.x - (uv.y * ratio)) * 0.5, (uv.x + (uv.y * ratio)) * 0.5);\n    vec4 texture_color = vec4(0.0350000001490116119384765625, 0.3689999878406524658203125, 0.72500002384185791015625, 1.0);\n    vec4 k = vec4(iTime) * 0.800000011920928955078125;\n    vec2 _71 = uv * 100.0;\n    k.x = _71.x;\n    k.y = _71.y;\n    vec4 _87 = k;\n    vec3 _89 = _87.xyw * mat3(vec3(-1.0, -0.5, 0.0), vec3(1.5, -0.5, 0.5), vec3(0.5, -0.5, -0.5));\n    k.x = _89.x;\n    k.y = _89.y;\n    k.w = _89.z;\n    float val1 = length(vec3(0.5) - fract(_89));\n    vec4 _110 = k;\n    vec3 _112 = _110.xyw * mat3(vec3(-0.4000000059604644775390625, -0.20000000298023223876953125, 0.0), vec3(0.60000002384185791015625, -0.20000000298023223876953125, 0.20000000298023223876953125), vec3(0.20000000298023223876953125, -0.20000000298023223876953125, -0.20000000298023223876953125));\n    k.x = _112.x;\n    k.y = _112.y;\n    k.w = _112.z;\n    float val2 = length(vec3(0.5) - fract(_112));\n    vec4 _124 = k;\n    vec3 _126 = _124.xyw * mat3(vec3(-1.0, -0.5, 0.0), vec3(1.5, -0.5, 0.5), vec3(0.5, -0.5, -0.5));\n    k.x = _126.x;\n    k.y = _126.y;\n    k.w = _126.z;\n    float val3 = length(vec3(0.5) - fract(_126));\n    float alpha = 0.949999988079071044921875;\n    vec3 rgbColor = vec3(pow(min(min(val1, val2), val3), 7.0) * 1.0) + texture_color.xyz;\n    fragColor = vec4(rgbColor, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 0,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "iResolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "iTime",
      "rows": 1,
      "type": 10
    }
  ]
}