{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float iTime;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 pixelSize = vec2(10.0);\n    vec2 reducedResolution = vec2(10.0, 5.0) / pixelSize;\n    vec2 uv = floor(flutter_FragCoord.xy / pixelSize) / reducedResolution;\n    vec3 col = vec3(0.0);\n    float wave = sin((uv.y * 4.0) + (iTime * 0.5)) * 0.100000001490116119384765625;\n    wave += 0.100000001490116119384765625;\n    vec3 waterColor = vec3(0.100000001490116119384765625, 0.300000011920928955078125, 0.5);\n    col = waterColor + vec3(wave);\n    fragColor = vec4(col, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "iTime",
      "rows": 1,
      "type": 10
    }
  ]
}